[package]
name = "trie"
version = "0.1.0"
edition = "2021"
authors = ["Jacob S. Porter"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
